# Generated by Django 4.2.7 on 2023-11-26 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('images', models.ImageField(blank=True, null=True, upload_to='artist_images')),
            ],
            options={
                'verbose_name_plural': 'Artist',
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=15)),
                ('images', models.ImageField(blank=True, null=True, upload_to='songimages')),
                ('lyrics', models.TextField(blank=True, max_length=10000, null=True)),
                ('rating', models.IntegerField()),
                ('genre', models.CharField(choices=[('B', 'Blues'), ('AB', 'Afrobeats'), ('C', 'Country'), ('P', 'POP'), ('HP', 'HIP HOP')], max_length=5)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.artist')),
            ],
            options={
                'verbose_name_plural': 'Songs',
            },
        ),
    ]
