# Generated by Django 4.2.7 on 2023-11-26 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_alter_songs_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='title',
            new_name='name',
        ),
    ]
